apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rmj37k7c5k0ch2s58e0n48lljzgm3yty0fxvxz5vldcd7dtt45xqkgdrfg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVUNNZ2FQNDk4SWVoNlIv
            a0puMkk0YlNkVHhYZTRWZ2g5SjFxd1hBQWlzCk5ZblZVSGdDTDlxZjhQOE84Uld0
            aVlEYzJYclhKbldnUkZ6ZTAvaC9ybWsKLS0tIERMNVYxenk3enFFNmNIYUJwV25z
            emF2bnRtcmZvRXpQb2xrWmlyaFZLdmsKTeYtmQoUG+1yJX4E42kz3ja5mRCEsh9R
            7txxxQwhhzM/LQv9Ro2w3rNlLjivC+jomAoeCNHVzFSX14+aQAa0Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T02:41:49Z"
    mac: ENC[AES256_GCM,data:98W36aTcIUit1r2RsOUSRUco70AdMqucCGQAmI87PAzeKLyDKFCCb98lR9t3sKtmFqJycMY316zbbJ380flm9DGfuTIO4/qgEVYaKc8N8NBjbHoTeDd2LgSwdaXTynqr8nriXVtGjTmxULwkXAPLifY07NgfNUBXKeia3zEWlzo=,iv:RY/xFfCAS34ATtOumZGA9IgiSzoX/+myZp1Mo1G6eb0=,tag:0XDoTd9dxD68Iv+qAa18rA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
